spring.application.name=printnow
spring.datasource.url=jdbc:mysql://localhost:3306/printnow_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=printnow_user
spring.datasource.password=printnow_password
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update