spring.application.name=printnow
spring.jackson.serialization.write-dates-as-timestamps=false
spring.datasource.url=jdbc:mysql://localhost:3306/printnow_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=printnow_user
spring.datasource.password=printnow_password
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
stripe.api.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=whsec_8d000bac6c9efef0190bf846e18722f72a7576b3a1306b4adccf0fca3b6e9327

# Upload fichiers PDF
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
app.upload.dir=uploads

# Inclure le message d'erreur dans les réponses HTTP
server.error.include-message=always

# AfterShipping (suivi bpost)
aftershipping.api.key=asat_d58d71f67af8453e888ed7a674354c2e
aftershipping.base.url=https://api.aftership.com/v4
aftershipping.courier.slug=bpost

# Mistral (modération IA gratuite des commentaires d'avis)
mistral.api.key=eTX7lcZ7YudlnQmzNvsgvGVUthw3yRaW
mistral.base.url=https://api.mistral.ai/v1
mistral.model=mistral-small-latest